name: CI

"on": [push, pull_request, schedule]
      - cron: " 5 1,3,17,19,21,23 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"

      - name: condaenv
        run: |
          conda init bash
          conda create --name docsteady-env docsteady -c lsst-dm -c conda-forge
        shell: bash

      - name: docugen
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
          JIRA_DB: ${{ secrets.JIRA_DB }}
          JIRA_VCD_USER: ${{ secrets.JIRA_VCD_USER }}
          JIRA_VCD_PASSWORD: ${{ secrets.JIRA_VCD_PASSWORD }}
        run: |
          conda info --envs
          source ${CONDA}/bin/activate docsteady-env
          docsteady  generate-vcd  jira_docugen.tex
        shell: bash


      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf LDM-692.pdf --lsstdoc LDM-692.tex --ltd-product ldm-692
